# Generated by Django 5.0.3 on 2025-02-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_trainers_joinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experianse_level',
            field=models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], default='beginner', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'lose_weight'), ('build_muscle', 'build_muscle'), ('endurance', 'endurance')], default='build_muscle', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('coach', 'coach'), ('trainer', 'trainer')], default='trainer', max_length=15, null=True),
        ),
    ]
