"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@pz57mwde#l)1#d(hu654$6j*(^q2yp@r_yinyhcyph6t64wp9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'authapp.apps.AuthappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'posts',
    'exercises',
    'health',
    'chatapp',
    'channels',
    'notification',
    "corsheaders",

]

ASGI_APPLICATION = "project.asgi.application"

# Use in-memory channel layer for now (for production you’d want Redis)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# img cloud storage
import cloudinary
cloudinary.config(
    cloud_name = 'dihberqmu',
    api_key = '139238618629431',
    api_secret = 'HYAtd2lbAQJdF8q0foLgpnI_e9Q'
)

# sittings
SIMPLE_JWT ={
    'ACCESS_TOKEN_LIFETIME':timedelta(days=365),
    #'REFRESH_TOKEN_LIFETIME':timedelta(days=1),
    #'BLACKLIST_AFTER_ROTATION':True,
    #'AUTH_HEADER_TYPES':('Bearer',),
    #'AUTH_TOKEN_CLASSES':('rest_framework_simplejwt.tokens.AccessToken',),
}



MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://mj202.netlify.app/"
    "https://render-project1-qyk2.onrender.com",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://render-project1-qyk2.onrender.com",
    "https://mj202.netlify.app/"
]

CORS_ALLOW_CREDENTIALS = True 
ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
## onesignal settings
ONESIGNAL_APP_ID = "be23165a-a4b3-49ce-a6bd-3e094d815cef"
ONESIGNAL_API_KEY = "os_v2_app_xyrrmwvewne45jv5hyeu3ak455vqvqrqrvhuyjmsmxisgssmvglxgfmpn7hhb3z4xpzlqu4ozkqdctrcgxcfax3k67qtg7mnp726mfq"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "markoriobrazil@gmail.com"
# EMAIL_HOST_PASSWORD = "awds hhuk dvnz fapi"
# ADMIN_EMAIL = "md3393911@gmail.com"



# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.example.com")
# EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
# EMAIL_HOST_USER = "markoriobrazil@gmail.com"   # always use this
# EMAIL_HOST_PASSWORD = "awds hhuk dvnz fapi"
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False

# # Fixed sender and receiver
# DEFAULT_FROM_EMAIL = "markoriobrazil@gmail.com"
# ADMIN_EMAIL = "md3393911@gmail.com"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------- Email Settings ----------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False  # Gmail uses TLS on port 587
EMAIL_HOST_USER = "markoriobrazil@gmail.com"
EMAIL_HOST_PASSWORD = "awds hhuk dvnz fapi"  # Use Gmail App Password

# Always send from this email
DEFAULT_FROM_EMAIL = "markoriobrazil@gmail.com"

# Always send to this email
ADMIN_EMAIL = "md3393911@gmail.com"