# Generated by Django 5.2.2 on 2025-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(default='4_3', max_length=255),
            preserve_default=False,
        ),
    ]
