# Generated by Django 5.1.7 on 2025-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='machine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
