# Generated by Django 5.1.7 on 2025-05-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='machine',
        ),
    ]
