# Generated by Django 5.2.2 on 2025-09-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercise_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
