# Generated by Django 5.1.7 on 2025-05-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('dietplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.dietplan')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.meal')),
            ],
        ),
    ]
