# Generated by Django 5.1.7 on 2025-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_mealsschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealsschedule',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
